name: flutter_training
description: YUMEMI Inc. flutter training app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  go_router: ^6.5.5
  hooks_riverpod: ^2.3.4
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.4
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  blendthink_lints: ^3.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.2.0
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
